FROM python:3.6
LABEL maintainer="qzclinux <qzclinux@163.com>" date="20230520"
RUN mkdir /data && rm -f /etc/localtime \
&& ln -sv /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
&& echo "Asia/Shanghai" > /etc/timezone  \
&& pip install -i https://pypi.tuna.tsinghua.edu.cn/simple tensorflow-cpu==2.6.1 tensorflow-addons==0.10.0 requests==2.22.0 keras==2.6.0 beautifulsoup4==4.9.3 pandas==1.0.0 numpy==1.19.5 lxml==4.6.2 loguru==0.6.0 grpcio==1.46.0 protobuf==3.18.1
ADD . /data
WORKDIR /data
##双色球
CMD ["sh", "./run_scripts.sh", "ssq"]
##大乐透
#CMD ["sh", "./run_scripts.sh", "dlt"]
